apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      # imagePullSecrets:
        # - name: ghcr-credentials
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres1!@db:5432/hebrew_feasts
            - name: TZ
              value: "UTC"
            # - name: OPENAPI_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: api-secrets
            #       key: OPENAPI_KEY
            - name: SERVER_PORT
              value: "8080"
          # image: docker.io/ryanostrom/ara-dev-api:latest
          image: ghcr.io/anon-r-7/hebrew-feasts-api:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - >
                nc -z -w 5 db 5432 || exit 1
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
