name: Build and Test
on: [push]

jobs:
  api:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node.js '20'
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier

      - name: Test
        run: yarn test

      - name: Build API
        run: yarn build
        working-directory: packages/api

      - name: Build UI
        run: yarn build
        working-directory: packages/ui
