name: Build and publish a Docker image
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  api:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/ara-dev-api:latest -f api.dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/ara-dev-api:latest

      # Use ghcr once github resolve issue with container registry
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}-api
          dockerfile: "api.dockerfile"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Auto update Digital Ocean when new tag is pulled in
      # - name: Update DigitalOcean App with new image
      #   run: |
      #     DO_APP_ID="your-app-id" # Replace with your DigitalOcean App ID
      #     DO_IMAGE="ghcr.io/${{ github.repository }}-api:${{ github.ref_name }}"
      #     curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -d "{\"image\":\"$DO_IMAGE\"}" "https://api.digitalocean.com/v2/apps/$DO_APP_ID"

  ui:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_USERNAME }}/ara-dev-ui:latest -f ui.dockerfile .
      #     docker push ${{ secrets.DOCKER_USERNAME }}/ara-dev-ui:latest

      # Use ghcr once github resolve issue with container registry
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}-ui
          dockerfile: "ui.dockerfile"
          github_token: ${{ secrets.GITHUB_TOKEN }}
 
      # Auto update Digital Ocean when new tag is pulled in
      # - name: Update DigitalOcean App with new image
      #   run: |
      #     DO_APP_ID="your-app-id" # Replace with your DigitalOcean App ID
      #     DO_IMAGE="ghcr.io/${{ github.repository }}-ui:${{ github.ref_name }}"
      #     curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -d "{\"image\":\"$DO_IMAGE\"}" "https://api.digitalocean.com/v2/apps/$DO_APP_ID"


