name: Build and publish a Docker image
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  api:
    runs-on: "ubuntu-20.04"
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: api.dockerfile
          push: true

      # Auto update Digital Ocean when new tag is pulled in
      # - name: Update DigitalOcean App with new image
      #   run: |
      #     DO_APP_ID="your-app-id" # Replace with your DigitalOcean App ID
      #     DO_IMAGE="ghcr.io/${{ github.repository }}-api:${{ github.ref_name }}"
      #     curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -d "{\"image\":\"$DO_IMAGE\"}" "https://api.digitalocean.com/v2/apps/$DO_APP_ID"

  ui:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ui.dockerfile
          push: true

      # Auto update Digital Ocean when new tag is pulled in
      # - name: Update DigitalOcean App with new image
      #   run: |
      #     DO_APP_ID="your-app-id" # Replace with your DigitalOcean App ID
      #     DO_IMAGE="ghcr.io/${{ github.repository }}-ui:${{ github.ref_name }}"
      #     curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" -d "{\"image\":\"$DO_IMAGE\"}" "https://api.digitalocean.com/v2/apps/$DO_APP_ID"


